# Generated by Django 5.2.7 on 2025-10-29 17:35

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tweetimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetimage',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '500x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
